<form class="form" id="custom-form" method="post" autocomplete="off" action="<?= $block->getUrl('retaildirect_giftclaim/index/submit') ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= __('Claim Your Gift') ?></span></legend><br>

        <input type="hidden" name="form_key" value="<?= $escaper->escapeHtml($block->getFormKey()) ?>">

        <div class="field required">
            <label for="imei" class="label"><span><?= __('IMEI') ?></span></label>
            <div class="control">
                <input
                    type="text"
                    name="imei"
                    id="imei"
                    value=""
                    title="<?= __('IMEI') ?>"
                    class="input-text"
                    data-validate="{required:true}"
                    aria-required="true"
                >
            </div>
        </div>

        <div class="field required">
            <label for="name" class="label"><span><?= __('Name') ?></span></label>
            <div class="control">
                <input
                    type="text"
                    name="name"
                    id="name"
                    value=""
                    title="<?= __('Name') ?>"
                    class="input-text"
                    data-validate="{required:true}"
                    aria-required="true"
                >
            </div>
        </div>

        <div class="field required">
            <label for="address" class="label"><span><?= __('Address') ?></span></label>
            <div class="control">
                <textarea
                    name="address"
                    id="address"
                    title="<?= __('Address') ?>"
                    class="input-text"
                    data-validate="{required:true}"
                    aria-required="true"
                ></textarea>
            </div>
        </div>

        <div class="field required">
            <label for="email_address" class="label"><span><?= __('Email') ?></span></label>
            <div class="control">
                <input
                    type="email"
                    name="email"
                    id="email_address"
                    value=""
                    title="<?= __('Email') ?>"
                    class="input-text"
                    data-validate="{required:true, 'validate-email':true}"
                    aria-required="true"
                >
            </div>
        </div>

        <div class="field required">
            <label for="phone" class="label"><span><?= __('Phone Number') ?></span></label>
            <div class="control">
                <input
                    type="tel"
                    name="phone"
                    id="phone"
                    value=""
                    title="<?= __('Phone Number') ?>"
                    class="input-text"
                    data-validate="{required:true, 'validate-number':true, 'minlength':10, 'maxlength':10}"
                    aria-required="true"
                >
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button
                type="submit"
                class="action submit primary"
                title="<?= __('Submit') ?>"
            >
                <span><?= __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>

<script type="text/x-magento-init">
{
    "#custom-form": {
        "validation": {}
    }
}
</script>
